server:
  port: 8082
spring:
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.11.38:5432/test
      username: tmax
      password: 1234
  jersey:
    type: filter